INITIAL_DROP:
- id
- date
- waterfront
- lat
- long

NUM_COLUMNS:
- bedrooms
- bathrooms
- sqft_living
- sqft_lot
- floors
- view
- sqft_above
- yr_built
- yr_renovated
- sqft_living15
- sqft_lot15
- sqft_basement

CAT_COLUMNS:
- condition
- grade
- zipcode

TARGET:
- price

TEST_SIZE:
  0.2

VIF_THRESHOLD:
  5

NUM_COLUMNS_SCALED:
  - bedrooms
  - bathrooms
  - sqft_lot
  - floors
  - view
  - yr_built
  - yr_renovated
  - sqft_living15
  - sqft_lot15

CAT_ENCODER:
  king-county-encoder.pkl

NUM_SCALER:
  king-county-scaler.pkl

MODEL_NAME:
  king-county-model.pkl

MODEL_BUCKET:
  jibbs-models
